name: Team_Work
version: 1.2.6
description: Plugin to manage teams on a serever! :D
author: Techmatt101
website: http://forums.bukkit.org/threads/team_work/
main: com.techmatt.teams.Teams
database: false

commands:
  team:
    description: Puts you into a Team!
    usage: /team [colour] OR /team will then randomly select a team
    
  team leave:
    description: Leave current Team
    usage: /team leave
    
  team spawn:
    description: Teleport to Team Spawn
    usage: /team spawn
    
  team list:
    description: List all Team members
    usage: /team list
    
  event:
    description: Manage events for teams
    usage: /event ?

  tc:
    description: To enable Team Chat
    usage: /tc
  
  spectate:
    description: Become a Spectator
    usage: /spectate
  
  ready:
    description: To shout that you Ready!