name: Team_Work
version: 1.3.0
description: Plugin to manage teams on a serever! :D
author: Techmatt101
website: http://forums.bukkit.org/threads/team_work/
main: com.techmatt.teams.Teams
database: false

commands:
  team:
    description: Team Manager Plugin
    usage: /<command> [join|leave|list|spawn|info]
    
  tc:
    description: To enable Team Chat
    usage: /tc
  
  spectate:
    description: Become a Spectator
    usage: /spectate
  
  ready:
    description: To shout that you Ready!